/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_test
#define _Included_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_test_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test
 * Method:    my_sqrt
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_test_my_1sqrt
  (JNIEnv *, jobject, jint);

/*
 * Class:     test
 * Method:    my_sin
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_test_my_1sin
  (JNIEnv *, jobject, jint);

/*
 * Class:     test
 * Method:    my_cos
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_test_my_1cos
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
